//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCardService.service.unicard.com {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardActiveResult", Namespace="http://UniCard.uni2uni.com/")]
    public enum CardActiveResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        激活失败 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        激活成功 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        找不到该订单激活记录 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        手机号码为空 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        订单号为空 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        激活码为空 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        激活码错误 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        手机号码错误 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        该订单已被激活过 = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://UniCard.uni2uni.com/", ConfigurationName="service.unicard.com.CardServicesSoap")]
    public interface CardServicesSoap {
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/CardLogin", ReplyAction="*")]
        UniCardService.service.unicard.com.CardLoginResponse CardLogin(UniCardService.service.unicard.com.CardLoginRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/PayLogin", ReplyAction="*")]
        UniCardService.service.unicard.com.PayLoginResponse PayLogin(UniCardService.service.unicard.com.PayLoginRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/Consume", ReplyAction="*")]
        UniCardService.service.unicard.com.ConsumeResponse Consume(UniCardService.service.unicard.com.ConsumeRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/ConsumeCancel", ReplyAction="*")]
        UniCardService.service.unicard.com.ConsumeCancelResponse ConsumeCancel(UniCardService.service.unicard.com.ConsumeCancelRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/Delivery", ReplyAction="*")]
        UniCardService.service.unicard.com.DeliveryResponse Delivery(UniCardService.service.unicard.com.DeliveryRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/DeliveryList", ReplyAction="*")]
        UniCardService.service.unicard.com.DeliveryListResponse DeliveryList(UniCardService.service.unicard.com.DeliveryListRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetAllCardType", ReplyAction="*")]
        UniCardService.service.unicard.com.GetAllCardTypeResponse GetAllCardType(UniCardService.service.unicard.com.GetAllCardTypeRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetCardType", ReplyAction="*")]
        UniCardService.service.unicard.com.GetCardTypeResponse GetCardType(UniCardService.service.unicard.com.GetCardTypeRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetPayRecord", ReplyAction="*")]
        UniCardService.service.unicard.com.GetPayRecordResponse GetPayRecord(UniCardService.service.unicard.com.GetPayRecordRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetPayByUserData", ReplyAction="*")]
        UniCardService.service.unicard.com.GetPayByUserDataResponse GetPayByUserData(UniCardService.service.unicard.com.GetPayByUserDataRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetGoodsRecord", ReplyAction="*")]
        UniCardService.service.unicard.com.GetGoodsRecordResponse GetGoodsRecord(UniCardService.service.unicard.com.GetGoodsRecordRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetCardTree", ReplyAction="*")]
        UniCardService.service.unicard.com.GetCardTreeResponse GetCardTree(UniCardService.service.unicard.com.GetCardTreeRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetTypeTree", ReplyAction="*")]
        UniCardService.service.unicard.com.GetTypeTreeResponse GetTypeTree(UniCardService.service.unicard.com.GetTypeTreeRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetTopicGiftCardList", ReplyAction="*")]
        UniCardService.service.unicard.com.GetTopicGiftCardListResponse GetTopicGiftCardList(UniCardService.service.unicard.com.GetTopicGiftCardListRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 sXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/PayActive", ReplyAction="*")]
        UniCardService.service.unicard.com.PayActiveResponse PayActive(UniCardService.service.unicard.com.PayActiveRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 strCardNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetCardSendLogByCardNo", ReplyAction="*")]
        UniCardService.service.unicard.com.GetCardSendLogByCardNoResponse GetCardSendLogByCardNo(UniCardService.service.unicard.com.GetCardSendLogByCardNoRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 strRelatedId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetActiveCodeByRelatedId", ReplyAction="*")]
        UniCardService.service.unicard.com.GetActiveCodeByRelatedIdResponse GetActiveCodeByRelatedId(UniCardService.service.unicard.com.GetActiveCodeByRelatedIdRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 strRelatedId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/GetMobileByRelatedId", ReplyAction="*")]
        UniCardService.service.unicard.com.GetMobileByRelatedIdResponse GetMobileByRelatedId(UniCardService.service.unicard.com.GetMobileByRelatedIdRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 strRelatedId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/CardActive", ReplyAction="*")]
        UniCardService.service.unicard.com.CardActiveResponse CardActive(UniCardService.service.unicard.com.CardActiveRequest request);
        
        // CODEGEN: 命名空间 http://UniCard.uni2uni.com/ 的元素名称 strRelatedId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UniCard.uni2uni.com/ValidateMobileAndActiveCard", ReplyAction="*")]
        UniCardService.service.unicard.com.ValidateMobileAndActiveCardResponse ValidateMobileAndActiveCard(UniCardService.service.unicard.com.ValidateMobileAndActiveCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CardLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CardLogin", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.CardLoginRequestBody Body;
        
        public CardLoginRequest() {
        }
        
        public CardLoginRequest(UniCardService.service.unicard.com.CardLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class CardLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public CardLoginRequestBody() {
        }
        
        public CardLoginRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CardLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CardLoginResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.CardLoginResponseBody Body;
        
        public CardLoginResponse() {
        }
        
        public CardLoginResponse(UniCardService.service.unicard.com.CardLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class CardLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CardLoginResult;
        
        public CardLoginResponseBody() {
        }
        
        public CardLoginResponseBody(string CardLoginResult) {
            this.CardLoginResult = CardLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayLogin", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.PayLoginRequestBody Body;
        
        public PayLoginRequest() {
        }
        
        public PayLoginRequest(UniCardService.service.unicard.com.PayLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class PayLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public PayLoginRequestBody() {
        }
        
        public PayLoginRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayLoginResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.PayLoginResponseBody Body;
        
        public PayLoginResponse() {
        }
        
        public PayLoginResponse(UniCardService.service.unicard.com.PayLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class PayLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PayLoginResult;
        
        public PayLoginResponseBody() {
        }
        
        public PayLoginResponseBody(string PayLoginResult) {
            this.PayLoginResult = PayLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsumeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consume", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.ConsumeRequestBody Body;
        
        public ConsumeRequest() {
        }
        
        public ConsumeRequest(UniCardService.service.unicard.com.ConsumeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class ConsumeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public ConsumeRequestBody() {
        }
        
        public ConsumeRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsumeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsumeResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.ConsumeResponseBody Body;
        
        public ConsumeResponse() {
        }
        
        public ConsumeResponse(UniCardService.service.unicard.com.ConsumeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class ConsumeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsumeResult;
        
        public ConsumeResponseBody() {
        }
        
        public ConsumeResponseBody(string ConsumeResult) {
            this.ConsumeResult = ConsumeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsumeCancelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsumeCancel", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.ConsumeCancelRequestBody Body;
        
        public ConsumeCancelRequest() {
        }
        
        public ConsumeCancelRequest(UniCardService.service.unicard.com.ConsumeCancelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class ConsumeCancelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public ConsumeCancelRequestBody() {
        }
        
        public ConsumeCancelRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsumeCancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsumeCancelResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.ConsumeCancelResponseBody Body;
        
        public ConsumeCancelResponse() {
        }
        
        public ConsumeCancelResponse(UniCardService.service.unicard.com.ConsumeCancelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class ConsumeCancelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsumeCancelResult;
        
        public ConsumeCancelResponseBody() {
        }
        
        public ConsumeCancelResponseBody(string ConsumeCancelResult) {
            this.ConsumeCancelResult = ConsumeCancelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delivery", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.DeliveryRequestBody Body;
        
        public DeliveryRequest() {
        }
        
        public DeliveryRequest(UniCardService.service.unicard.com.DeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class DeliveryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public DeliveryRequestBody() {
        }
        
        public DeliveryRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.DeliveryResponseBody Body;
        
        public DeliveryResponse() {
        }
        
        public DeliveryResponse(UniCardService.service.unicard.com.DeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class DeliveryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeliveryResult;
        
        public DeliveryResponseBody() {
        }
        
        public DeliveryResponseBody(string DeliveryResult) {
            this.DeliveryResult = DeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryList", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.DeliveryListRequestBody Body;
        
        public DeliveryListRequest() {
        }
        
        public DeliveryListRequest(UniCardService.service.unicard.com.DeliveryListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class DeliveryListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public DeliveryListRequestBody() {
        }
        
        public DeliveryListRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryListResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.DeliveryListResponseBody Body;
        
        public DeliveryListResponse() {
        }
        
        public DeliveryListResponse(UniCardService.service.unicard.com.DeliveryListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class DeliveryListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeliveryListResult;
        
        public DeliveryListResponseBody() {
        }
        
        public DeliveryListResponseBody(string DeliveryListResult) {
            this.DeliveryListResult = DeliveryListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCardTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCardType", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetAllCardTypeRequestBody Body;
        
        public GetAllCardTypeRequest() {
        }
        
        public GetAllCardTypeRequest(UniCardService.service.unicard.com.GetAllCardTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetAllCardTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public GetAllCardTypeRequestBody() {
        }
        
        public GetAllCardTypeRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCardTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCardTypeResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetAllCardTypeResponseBody Body;
        
        public GetAllCardTypeResponse() {
        }
        
        public GetAllCardTypeResponse(UniCardService.service.unicard.com.GetAllCardTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetAllCardTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllCardTypeResult;
        
        public GetAllCardTypeResponseBody() {
        }
        
        public GetAllCardTypeResponseBody(string GetAllCardTypeResult) {
            this.GetAllCardTypeResult = GetAllCardTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCardTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCardType", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetCardTypeRequestBody Body;
        
        public GetCardTypeRequest() {
        }
        
        public GetCardTypeRequest(UniCardService.service.unicard.com.GetCardTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetCardTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public GetCardTypeRequestBody() {
        }
        
        public GetCardTypeRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCardTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCardTypeResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetCardTypeResponseBody Body;
        
        public GetCardTypeResponse() {
        }
        
        public GetCardTypeResponse(UniCardService.service.unicard.com.GetCardTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetCardTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCardTypeResult;
        
        public GetCardTypeResponseBody() {
        }
        
        public GetCardTypeResponseBody(string GetCardTypeResult) {
            this.GetCardTypeResult = GetCardTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPayRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPayRecord", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetPayRecordRequestBody Body;
        
        public GetPayRecordRequest() {
        }
        
        public GetPayRecordRequest(UniCardService.service.unicard.com.GetPayRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetPayRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public GetPayRecordRequestBody() {
        }
        
        public GetPayRecordRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPayRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPayRecordResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetPayRecordResponseBody Body;
        
        public GetPayRecordResponse() {
        }
        
        public GetPayRecordResponse(UniCardService.service.unicard.com.GetPayRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetPayRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPayRecordResult;
        
        public GetPayRecordResponseBody() {
        }
        
        public GetPayRecordResponseBody(string GetPayRecordResult) {
            this.GetPayRecordResult = GetPayRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPayByUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPayByUserData", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetPayByUserDataRequestBody Body;
        
        public GetPayByUserDataRequest() {
        }
        
        public GetPayByUserDataRequest(UniCardService.service.unicard.com.GetPayByUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetPayByUserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public GetPayByUserDataRequestBody() {
        }
        
        public GetPayByUserDataRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPayByUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPayByUserDataResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetPayByUserDataResponseBody Body;
        
        public GetPayByUserDataResponse() {
        }
        
        public GetPayByUserDataResponse(UniCardService.service.unicard.com.GetPayByUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetPayByUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPayByUserDataResult;
        
        public GetPayByUserDataResponseBody() {
        }
        
        public GetPayByUserDataResponseBody(string GetPayByUserDataResult) {
            this.GetPayByUserDataResult = GetPayByUserDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsRecord", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetGoodsRecordRequestBody Body;
        
        public GetGoodsRecordRequest() {
        }
        
        public GetGoodsRecordRequest(UniCardService.service.unicard.com.GetGoodsRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetGoodsRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public GetGoodsRecordRequestBody() {
        }
        
        public GetGoodsRecordRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsRecordResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetGoodsRecordResponseBody Body;
        
        public GetGoodsRecordResponse() {
        }
        
        public GetGoodsRecordResponse(UniCardService.service.unicard.com.GetGoodsRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetGoodsRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGoodsRecordResult;
        
        public GetGoodsRecordResponseBody() {
        }
        
        public GetGoodsRecordResponseBody(string GetGoodsRecordResult) {
            this.GetGoodsRecordResult = GetGoodsRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCardTreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCardTree", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetCardTreeRequestBody Body;
        
        public GetCardTreeRequest() {
        }
        
        public GetCardTreeRequest(UniCardService.service.unicard.com.GetCardTreeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetCardTreeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public GetCardTreeRequestBody() {
        }
        
        public GetCardTreeRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCardTreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCardTreeResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetCardTreeResponseBody Body;
        
        public GetCardTreeResponse() {
        }
        
        public GetCardTreeResponse(UniCardService.service.unicard.com.GetCardTreeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetCardTreeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCardTreeResult;
        
        public GetCardTreeResponseBody() {
        }
        
        public GetCardTreeResponseBody(string GetCardTreeResult) {
            this.GetCardTreeResult = GetCardTreeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTypeTreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTypeTree", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetTypeTreeRequestBody Body;
        
        public GetTypeTreeRequest() {
        }
        
        public GetTypeTreeRequest(UniCardService.service.unicard.com.GetTypeTreeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetTypeTreeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public GetTypeTreeRequestBody() {
        }
        
        public GetTypeTreeRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTypeTreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTypeTreeResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetTypeTreeResponseBody Body;
        
        public GetTypeTreeResponse() {
        }
        
        public GetTypeTreeResponse(UniCardService.service.unicard.com.GetTypeTreeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetTypeTreeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTypeTreeResult;
        
        public GetTypeTreeResponseBody() {
        }
        
        public GetTypeTreeResponseBody(string GetTypeTreeResult) {
            this.GetTypeTreeResult = GetTypeTreeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopicGiftCardListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopicGiftCardList", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetTopicGiftCardListRequestBody Body;
        
        public GetTopicGiftCardListRequest() {
        }
        
        public GetTopicGiftCardListRequest(UniCardService.service.unicard.com.GetTopicGiftCardListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetTopicGiftCardListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public GetTopicGiftCardListRequestBody() {
        }
        
        public GetTopicGiftCardListRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopicGiftCardListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopicGiftCardListResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetTopicGiftCardListResponseBody Body;
        
        public GetTopicGiftCardListResponse() {
        }
        
        public GetTopicGiftCardListResponse(UniCardService.service.unicard.com.GetTopicGiftCardListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetTopicGiftCardListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTopicGiftCardListResult;
        
        public GetTopicGiftCardListResponseBody() {
        }
        
        public GetTopicGiftCardListResponseBody(string GetTopicGiftCardListResult) {
            this.GetTopicGiftCardListResult = GetTopicGiftCardListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayActiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayActive", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.PayActiveRequestBody Body;
        
        public PayActiveRequest() {
        }
        
        public PayActiveRequest(UniCardService.service.unicard.com.PayActiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class PayActiveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXml;
        
        public PayActiveRequestBody() {
        }
        
        public PayActiveRequestBody(string sXml) {
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayActiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayActiveResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.PayActiveResponseBody Body;
        
        public PayActiveResponse() {
        }
        
        public PayActiveResponse(UniCardService.service.unicard.com.PayActiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class PayActiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PayActiveResult;
        
        public PayActiveResponseBody() {
        }
        
        public PayActiveResponseBody(string PayActiveResult) {
            this.PayActiveResult = PayActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCardSendLogByCardNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCardSendLogByCardNo", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetCardSendLogByCardNoRequestBody Body;
        
        public GetCardSendLogByCardNoRequest() {
        }
        
        public GetCardSendLogByCardNoRequest(UniCardService.service.unicard.com.GetCardSendLogByCardNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetCardSendLogByCardNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCardNo;
        
        public GetCardSendLogByCardNoRequestBody() {
        }
        
        public GetCardSendLogByCardNoRequestBody(string strCardNo) {
            this.strCardNo = strCardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCardSendLogByCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCardSendLogByCardNoResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetCardSendLogByCardNoResponseBody Body;
        
        public GetCardSendLogByCardNoResponse() {
        }
        
        public GetCardSendLogByCardNoResponse(UniCardService.service.unicard.com.GetCardSendLogByCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetCardSendLogByCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCardSendLogByCardNoResult;
        
        public GetCardSendLogByCardNoResponseBody() {
        }
        
        public GetCardSendLogByCardNoResponseBody(string GetCardSendLogByCardNoResult) {
            this.GetCardSendLogByCardNoResult = GetCardSendLogByCardNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveCodeByRelatedIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveCodeByRelatedId", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetActiveCodeByRelatedIdRequestBody Body;
        
        public GetActiveCodeByRelatedIdRequest() {
        }
        
        public GetActiveCodeByRelatedIdRequest(UniCardService.service.unicard.com.GetActiveCodeByRelatedIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetActiveCodeByRelatedIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strRelatedId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strValidateCode;
        
        public GetActiveCodeByRelatedIdRequestBody() {
        }
        
        public GetActiveCodeByRelatedIdRequestBody(string strRelatedId, string strValidateCode) {
            this.strRelatedId = strRelatedId;
            this.strValidateCode = strValidateCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveCodeByRelatedIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveCodeByRelatedIdResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetActiveCodeByRelatedIdResponseBody Body;
        
        public GetActiveCodeByRelatedIdResponse() {
        }
        
        public GetActiveCodeByRelatedIdResponse(UniCardService.service.unicard.com.GetActiveCodeByRelatedIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetActiveCodeByRelatedIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActiveCodeByRelatedIdResult;
        
        public GetActiveCodeByRelatedIdResponseBody() {
        }
        
        public GetActiveCodeByRelatedIdResponseBody(string GetActiveCodeByRelatedIdResult) {
            this.GetActiveCodeByRelatedIdResult = GetActiveCodeByRelatedIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMobileByRelatedIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMobileByRelatedId", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetMobileByRelatedIdRequestBody Body;
        
        public GetMobileByRelatedIdRequest() {
        }
        
        public GetMobileByRelatedIdRequest(UniCardService.service.unicard.com.GetMobileByRelatedIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetMobileByRelatedIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strRelatedId;
        
        public GetMobileByRelatedIdRequestBody() {
        }
        
        public GetMobileByRelatedIdRequestBody(string strRelatedId) {
            this.strRelatedId = strRelatedId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMobileByRelatedIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMobileByRelatedIdResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.GetMobileByRelatedIdResponseBody Body;
        
        public GetMobileByRelatedIdResponse() {
        }
        
        public GetMobileByRelatedIdResponse(UniCardService.service.unicard.com.GetMobileByRelatedIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class GetMobileByRelatedIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMobileByRelatedIdResult;
        
        public GetMobileByRelatedIdResponseBody() {
        }
        
        public GetMobileByRelatedIdResponseBody(string GetMobileByRelatedIdResult) {
            this.GetMobileByRelatedIdResult = GetMobileByRelatedIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CardActiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CardActive", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.CardActiveRequestBody Body;
        
        public CardActiveRequest() {
        }
        
        public CardActiveRequest(UniCardService.service.unicard.com.CardActiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class CardActiveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strRelatedId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strActiveCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string appId;
        
        public CardActiveRequestBody() {
        }
        
        public CardActiveRequestBody(string strRelatedId, string strActiveCode, string appId) {
            this.strRelatedId = strRelatedId;
            this.strActiveCode = strActiveCode;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CardActiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CardActiveResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.CardActiveResponseBody Body;
        
        public CardActiveResponse() {
        }
        
        public CardActiveResponse(UniCardService.service.unicard.com.CardActiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class CardActiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public UniCardService.service.unicard.com.CardActiveResult CardActiveResult;
        
        public CardActiveResponseBody() {
        }
        
        public CardActiveResponseBody(UniCardService.service.unicard.com.CardActiveResult CardActiveResult) {
            this.CardActiveResult = CardActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateMobileAndActiveCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateMobileAndActiveCard", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.ValidateMobileAndActiveCardRequestBody Body;
        
        public ValidateMobileAndActiveCardRequest() {
        }
        
        public ValidateMobileAndActiveCardRequest(UniCardService.service.unicard.com.ValidateMobileAndActiveCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class ValidateMobileAndActiveCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strRelatedId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strActiveCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string appId;
        
        public ValidateMobileAndActiveCardRequestBody() {
        }
        
        public ValidateMobileAndActiveCardRequestBody(string strRelatedId, string strActiveCode, string strMobile, string appId) {
            this.strRelatedId = strRelatedId;
            this.strActiveCode = strActiveCode;
            this.strMobile = strMobile;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateMobileAndActiveCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateMobileAndActiveCardResponse", Namespace="http://UniCard.uni2uni.com/", Order=0)]
        public UniCardService.service.unicard.com.ValidateMobileAndActiveCardResponseBody Body;
        
        public ValidateMobileAndActiveCardResponse() {
        }
        
        public ValidateMobileAndActiveCardResponse(UniCardService.service.unicard.com.ValidateMobileAndActiveCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UniCard.uni2uni.com/")]
    public partial class ValidateMobileAndActiveCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public UniCardService.service.unicard.com.CardActiveResult ValidateMobileAndActiveCardResult;
        
        public ValidateMobileAndActiveCardResponseBody() {
        }
        
        public ValidateMobileAndActiveCardResponseBody(UniCardService.service.unicard.com.CardActiveResult ValidateMobileAndActiveCardResult) {
            this.ValidateMobileAndActiveCardResult = ValidateMobileAndActiveCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CardServicesSoapChannel : UniCardService.service.unicard.com.CardServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardServicesSoapClient : System.ServiceModel.ClientBase<UniCardService.service.unicard.com.CardServicesSoap>, UniCardService.service.unicard.com.CardServicesSoap {
        
        public CardServicesSoapClient() {
        }
        
        public CardServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.CardLoginResponse UniCardService.service.unicard.com.CardServicesSoap.CardLogin(UniCardService.service.unicard.com.CardLoginRequest request) {
            return base.Channel.CardLogin(request);
        }
        
        public string CardLogin(string sXml) {
            UniCardService.service.unicard.com.CardLoginRequest inValue = new UniCardService.service.unicard.com.CardLoginRequest();
            inValue.Body = new UniCardService.service.unicard.com.CardLoginRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.CardLoginResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).CardLogin(inValue);
            return retVal.Body.CardLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.PayLoginResponse UniCardService.service.unicard.com.CardServicesSoap.PayLogin(UniCardService.service.unicard.com.PayLoginRequest request) {
            return base.Channel.PayLogin(request);
        }
        
        public string PayLogin(string sXml) {
            UniCardService.service.unicard.com.PayLoginRequest inValue = new UniCardService.service.unicard.com.PayLoginRequest();
            inValue.Body = new UniCardService.service.unicard.com.PayLoginRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.PayLoginResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).PayLogin(inValue);
            return retVal.Body.PayLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.ConsumeResponse UniCardService.service.unicard.com.CardServicesSoap.Consume(UniCardService.service.unicard.com.ConsumeRequest request) {
            return base.Channel.Consume(request);
        }
        
        public string Consume(string sXml) {
            UniCardService.service.unicard.com.ConsumeRequest inValue = new UniCardService.service.unicard.com.ConsumeRequest();
            inValue.Body = new UniCardService.service.unicard.com.ConsumeRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.ConsumeResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).Consume(inValue);
            return retVal.Body.ConsumeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.ConsumeCancelResponse UniCardService.service.unicard.com.CardServicesSoap.ConsumeCancel(UniCardService.service.unicard.com.ConsumeCancelRequest request) {
            return base.Channel.ConsumeCancel(request);
        }
        
        public string ConsumeCancel(string sXml) {
            UniCardService.service.unicard.com.ConsumeCancelRequest inValue = new UniCardService.service.unicard.com.ConsumeCancelRequest();
            inValue.Body = new UniCardService.service.unicard.com.ConsumeCancelRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.ConsumeCancelResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).ConsumeCancel(inValue);
            return retVal.Body.ConsumeCancelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.DeliveryResponse UniCardService.service.unicard.com.CardServicesSoap.Delivery(UniCardService.service.unicard.com.DeliveryRequest request) {
            return base.Channel.Delivery(request);
        }
        
        public string Delivery(string sXml) {
            UniCardService.service.unicard.com.DeliveryRequest inValue = new UniCardService.service.unicard.com.DeliveryRequest();
            inValue.Body = new UniCardService.service.unicard.com.DeliveryRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.DeliveryResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).Delivery(inValue);
            return retVal.Body.DeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.DeliveryListResponse UniCardService.service.unicard.com.CardServicesSoap.DeliveryList(UniCardService.service.unicard.com.DeliveryListRequest request) {
            return base.Channel.DeliveryList(request);
        }
        
        public string DeliveryList(string sXml) {
            UniCardService.service.unicard.com.DeliveryListRequest inValue = new UniCardService.service.unicard.com.DeliveryListRequest();
            inValue.Body = new UniCardService.service.unicard.com.DeliveryListRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.DeliveryListResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).DeliveryList(inValue);
            return retVal.Body.DeliveryListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetAllCardTypeResponse UniCardService.service.unicard.com.CardServicesSoap.GetAllCardType(UniCardService.service.unicard.com.GetAllCardTypeRequest request) {
            return base.Channel.GetAllCardType(request);
        }
        
        public string GetAllCardType(string sXml) {
            UniCardService.service.unicard.com.GetAllCardTypeRequest inValue = new UniCardService.service.unicard.com.GetAllCardTypeRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetAllCardTypeRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.GetAllCardTypeResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetAllCardType(inValue);
            return retVal.Body.GetAllCardTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetCardTypeResponse UniCardService.service.unicard.com.CardServicesSoap.GetCardType(UniCardService.service.unicard.com.GetCardTypeRequest request) {
            return base.Channel.GetCardType(request);
        }
        
        public string GetCardType(string sXml) {
            UniCardService.service.unicard.com.GetCardTypeRequest inValue = new UniCardService.service.unicard.com.GetCardTypeRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetCardTypeRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.GetCardTypeResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetCardType(inValue);
            return retVal.Body.GetCardTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetPayRecordResponse UniCardService.service.unicard.com.CardServicesSoap.GetPayRecord(UniCardService.service.unicard.com.GetPayRecordRequest request) {
            return base.Channel.GetPayRecord(request);
        }
        
        public string GetPayRecord(string sXml) {
            UniCardService.service.unicard.com.GetPayRecordRequest inValue = new UniCardService.service.unicard.com.GetPayRecordRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetPayRecordRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.GetPayRecordResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetPayRecord(inValue);
            return retVal.Body.GetPayRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetPayByUserDataResponse UniCardService.service.unicard.com.CardServicesSoap.GetPayByUserData(UniCardService.service.unicard.com.GetPayByUserDataRequest request) {
            return base.Channel.GetPayByUserData(request);
        }
        
        public string GetPayByUserData(string sXml) {
            UniCardService.service.unicard.com.GetPayByUserDataRequest inValue = new UniCardService.service.unicard.com.GetPayByUserDataRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetPayByUserDataRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.GetPayByUserDataResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetPayByUserData(inValue);
            return retVal.Body.GetPayByUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetGoodsRecordResponse UniCardService.service.unicard.com.CardServicesSoap.GetGoodsRecord(UniCardService.service.unicard.com.GetGoodsRecordRequest request) {
            return base.Channel.GetGoodsRecord(request);
        }
        
        public string GetGoodsRecord(string sXml) {
            UniCardService.service.unicard.com.GetGoodsRecordRequest inValue = new UniCardService.service.unicard.com.GetGoodsRecordRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetGoodsRecordRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.GetGoodsRecordResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetGoodsRecord(inValue);
            return retVal.Body.GetGoodsRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetCardTreeResponse UniCardService.service.unicard.com.CardServicesSoap.GetCardTree(UniCardService.service.unicard.com.GetCardTreeRequest request) {
            return base.Channel.GetCardTree(request);
        }
        
        public string GetCardTree(string sXml) {
            UniCardService.service.unicard.com.GetCardTreeRequest inValue = new UniCardService.service.unicard.com.GetCardTreeRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetCardTreeRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.GetCardTreeResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetCardTree(inValue);
            return retVal.Body.GetCardTreeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetTypeTreeResponse UniCardService.service.unicard.com.CardServicesSoap.GetTypeTree(UniCardService.service.unicard.com.GetTypeTreeRequest request) {
            return base.Channel.GetTypeTree(request);
        }
        
        public string GetTypeTree(string sXml) {
            UniCardService.service.unicard.com.GetTypeTreeRequest inValue = new UniCardService.service.unicard.com.GetTypeTreeRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetTypeTreeRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.GetTypeTreeResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetTypeTree(inValue);
            return retVal.Body.GetTypeTreeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetTopicGiftCardListResponse UniCardService.service.unicard.com.CardServicesSoap.GetTopicGiftCardList(UniCardService.service.unicard.com.GetTopicGiftCardListRequest request) {
            return base.Channel.GetTopicGiftCardList(request);
        }
        
        public string GetTopicGiftCardList(string sXml) {
            UniCardService.service.unicard.com.GetTopicGiftCardListRequest inValue = new UniCardService.service.unicard.com.GetTopicGiftCardListRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetTopicGiftCardListRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.GetTopicGiftCardListResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetTopicGiftCardList(inValue);
            return retVal.Body.GetTopicGiftCardListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.PayActiveResponse UniCardService.service.unicard.com.CardServicesSoap.PayActive(UniCardService.service.unicard.com.PayActiveRequest request) {
            return base.Channel.PayActive(request);
        }
        
        public string PayActive(string sXml) {
            UniCardService.service.unicard.com.PayActiveRequest inValue = new UniCardService.service.unicard.com.PayActiveRequest();
            inValue.Body = new UniCardService.service.unicard.com.PayActiveRequestBody();
            inValue.Body.sXml = sXml;
            UniCardService.service.unicard.com.PayActiveResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).PayActive(inValue);
            return retVal.Body.PayActiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetCardSendLogByCardNoResponse UniCardService.service.unicard.com.CardServicesSoap.GetCardSendLogByCardNo(UniCardService.service.unicard.com.GetCardSendLogByCardNoRequest request) {
            return base.Channel.GetCardSendLogByCardNo(request);
        }
        
        public string GetCardSendLogByCardNo(string strCardNo) {
            UniCardService.service.unicard.com.GetCardSendLogByCardNoRequest inValue = new UniCardService.service.unicard.com.GetCardSendLogByCardNoRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetCardSendLogByCardNoRequestBody();
            inValue.Body.strCardNo = strCardNo;
            UniCardService.service.unicard.com.GetCardSendLogByCardNoResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetCardSendLogByCardNo(inValue);
            return retVal.Body.GetCardSendLogByCardNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetActiveCodeByRelatedIdResponse UniCardService.service.unicard.com.CardServicesSoap.GetActiveCodeByRelatedId(UniCardService.service.unicard.com.GetActiveCodeByRelatedIdRequest request) {
            return base.Channel.GetActiveCodeByRelatedId(request);
        }
        
        public string GetActiveCodeByRelatedId(string strRelatedId, string strValidateCode) {
            UniCardService.service.unicard.com.GetActiveCodeByRelatedIdRequest inValue = new UniCardService.service.unicard.com.GetActiveCodeByRelatedIdRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetActiveCodeByRelatedIdRequestBody();
            inValue.Body.strRelatedId = strRelatedId;
            inValue.Body.strValidateCode = strValidateCode;
            UniCardService.service.unicard.com.GetActiveCodeByRelatedIdResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetActiveCodeByRelatedId(inValue);
            return retVal.Body.GetActiveCodeByRelatedIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.GetMobileByRelatedIdResponse UniCardService.service.unicard.com.CardServicesSoap.GetMobileByRelatedId(UniCardService.service.unicard.com.GetMobileByRelatedIdRequest request) {
            return base.Channel.GetMobileByRelatedId(request);
        }
        
        public string GetMobileByRelatedId(string strRelatedId) {
            UniCardService.service.unicard.com.GetMobileByRelatedIdRequest inValue = new UniCardService.service.unicard.com.GetMobileByRelatedIdRequest();
            inValue.Body = new UniCardService.service.unicard.com.GetMobileByRelatedIdRequestBody();
            inValue.Body.strRelatedId = strRelatedId;
            UniCardService.service.unicard.com.GetMobileByRelatedIdResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).GetMobileByRelatedId(inValue);
            return retVal.Body.GetMobileByRelatedIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.CardActiveResponse UniCardService.service.unicard.com.CardServicesSoap.CardActive(UniCardService.service.unicard.com.CardActiveRequest request) {
            return base.Channel.CardActive(request);
        }
        
        public UniCardService.service.unicard.com.CardActiveResult CardActive(string strRelatedId, string strActiveCode, string appId) {
            UniCardService.service.unicard.com.CardActiveRequest inValue = new UniCardService.service.unicard.com.CardActiveRequest();
            inValue.Body = new UniCardService.service.unicard.com.CardActiveRequestBody();
            inValue.Body.strRelatedId = strRelatedId;
            inValue.Body.strActiveCode = strActiveCode;
            inValue.Body.appId = appId;
            UniCardService.service.unicard.com.CardActiveResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).CardActive(inValue);
            return retVal.Body.CardActiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCardService.service.unicard.com.ValidateMobileAndActiveCardResponse UniCardService.service.unicard.com.CardServicesSoap.ValidateMobileAndActiveCard(UniCardService.service.unicard.com.ValidateMobileAndActiveCardRequest request) {
            return base.Channel.ValidateMobileAndActiveCard(request);
        }
        
        public UniCardService.service.unicard.com.CardActiveResult ValidateMobileAndActiveCard(string strRelatedId, string strActiveCode, string strMobile, string appId) {
            UniCardService.service.unicard.com.ValidateMobileAndActiveCardRequest inValue = new UniCardService.service.unicard.com.ValidateMobileAndActiveCardRequest();
            inValue.Body = new UniCardService.service.unicard.com.ValidateMobileAndActiveCardRequestBody();
            inValue.Body.strRelatedId = strRelatedId;
            inValue.Body.strActiveCode = strActiveCode;
            inValue.Body.strMobile = strMobile;
            inValue.Body.appId = appId;
            UniCardService.service.unicard.com.ValidateMobileAndActiveCardResponse retVal = ((UniCardService.service.unicard.com.CardServicesSoap)(this)).ValidateMobileAndActiveCard(inValue);
            return retVal.Body.ValidateMobileAndActiveCardResult;
        }
    }
}
