//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCinemaClubAPI.CinemaClubService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecretaryCard", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class SecretaryCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestCinemaClubAPI.CinemaClubService.ActiveCardResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestCinemaClubAPI.CinemaClubService.GetClubCardListResult))]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RstMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RstStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RstMsg {
            get {
                return this.RstMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.RstMsgField, value) != true)) {
                    this.RstMsgField = value;
                    this.RaisePropertyChanged("RstMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RstState {
            get {
                return this.RstStateField;
            }
            set {
                if ((this.RstStateField.Equals(value) != true)) {
                    this.RstStateField = value;
                    this.RaisePropertyChanged("RstState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveCardResult", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class ActiveCardResult : TestCinemaClubAPI.CinemaClubService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelatedIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedId {
            get {
                return this.RelatedIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedIdField, value) != true)) {
                    this.RelatedIdField = value;
                    this.RaisePropertyChanged("RelatedId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClubCardListResult", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class GetClubCardListResult : TestCinemaClubAPI.CinemaClubService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCinemaClubAPI.CinemaClubService.CardInfo[] ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCinemaClubAPI.CinemaClubService.CardInfo[] List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class CardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClubSeriesInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class ClubSeriesInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCinemaClubAPI.CinemaClubService.ExecuteInfo[] ExecListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCinemaClubAPI.CinemaClubService.MemberInfo MemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCinemaClubAPI.CinemaClubService.OrderInfo OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCinemaClubAPI.CinemaClubService.ExecuteInfo[] ExecList {
            get {
                return this.ExecListField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecListField, value) != true)) {
                    this.ExecListField = value;
                    this.RaisePropertyChanged("ExecList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCinemaClubAPI.CinemaClubService.MemberInfo Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestCinemaClubAPI.CinemaClubService.OrderInfo Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class MemberInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialsCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistrictIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CTypeId {
            get {
                return this.CTypeIdField;
            }
            set {
                if ((this.CTypeIdField.Equals(value) != true)) {
                    this.CTypeIdField = value;
                    this.RaisePropertyChanged("CTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID {
            get {
                return this.CityIDField;
            }
            set {
                if ((this.CityIDField.Equals(value) != true)) {
                    this.CityIDField = value;
                    this.RaisePropertyChanged("CityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialsCode {
            get {
                return this.CredentialsCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialsCodeField, value) != true)) {
                    this.CredentialsCodeField = value;
                    this.RaisePropertyChanged("CredentialsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistrictID {
            get {
                return this.DistrictIDField;
            }
            set {
                if ((this.DistrictIDField.Equals(value) != true)) {
                    this.DistrictIDField = value;
                    this.RaisePropertyChanged("DistrictID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealName {
            get {
                return this.RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RealNameField, value) != true)) {
                    this.RealNameField = value;
                    this.RaisePropertyChanged("RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClubType {
            get {
                return this.ClubTypeField;
            }
            set {
                if ((this.ClubTypeField.Equals(value) != true)) {
                    this.ClubTypeField = value;
                    this.RaisePropertyChanged("ClubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class ExecuteInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExecuteDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExecuteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecuteTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoblieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExecuteDate {
            get {
                return this.ExecuteDateField;
            }
            set {
                if ((this.ExecuteDateField.Equals(value) != true)) {
                    this.ExecuteDateField = value;
                    this.RaisePropertyChanged("ExecuteDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExecuteId {
            get {
                return this.ExecuteIdField;
            }
            set {
                if ((this.ExecuteIdField.Equals(value) != true)) {
                    this.ExecuteIdField = value;
                    this.RaisePropertyChanged("ExecuteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecuteType {
            get {
                return this.ExecuteTypeField;
            }
            set {
                if ((this.ExecuteTypeField.Equals(value) != true)) {
                    this.ExecuteTypeField = value;
                    this.RaisePropertyChanged("ExecuteType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moblie {
            get {
                return this.MoblieField;
            }
            set {
                if ((object.ReferenceEquals(this.MoblieField, value) != true)) {
                    this.MoblieField = value;
                    this.RaisePropertyChanged("Moblie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((this.OrderNumberField.Equals(value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((this.ProductCodeField.Equals(value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((this.ProductPriceField.Equals(value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CinemaCardInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class CinemaCardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CinemaTicketInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceForSecretaryCard")]
    [System.SerializableAttribute()]
    public partial class CinemaTicketInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieHallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieHouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreeningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieHall {
            get {
                return this.MovieHallField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieHallField, value) != true)) {
                    this.MovieHallField = value;
                    this.RaisePropertyChanged("MovieHall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieHouse {
            get {
                return this.MovieHouseField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieHouseField, value) != true)) {
                    this.MovieHouseField = value;
                    this.RaisePropertyChanged("MovieHouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieType {
            get {
                return this.MovieTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieTypeField, value) != true)) {
                    this.MovieTypeField = value;
                    this.RaisePropertyChanged("MovieType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Screening {
            get {
                return this.ScreeningField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreeningField, value) != true)) {
                    this.ScreeningField = value;
                    this.RaisePropertyChanged("Screening");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketCode {
            get {
                return this.TicketCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketCodeField, value) != true)) {
                    this.TicketCodeField = value;
                    this.RaisePropertyChanged("TicketCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CinemaClubService.ISecretaryCardSerivce")]
    public interface ISecretaryCardSerivce {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaryCardSerivce/GetSecretaryCardListByGeneralOrderId", ReplyAction="http://tempuri.org/ISecretaryCardSerivce/GetSecretaryCardListByGeneralOrderIdResp" +
            "onse")]
        TestCinemaClubAPI.CinemaClubService.SecretaryCard[] GetSecretaryCardListByGeneralOrderId(out string errMsg, string orderId, System.Guid operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaryCardSerivce/GetLifeClubCardListByGeneralOrderId", ReplyAction="http://tempuri.org/ISecretaryCardSerivce/GetLifeClubCardListByGeneralOrderIdRespo" +
            "nse")]
        TestCinemaClubAPI.CinemaClubService.GetClubCardListResult GetLifeClubCardListByGeneralOrderId(string orderId, System.Guid operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaryCardSerivce/GetLifeClubCardListByGeneralOrderIdNoOp", ReplyAction="http://tempuri.org/ISecretaryCardSerivce/GetLifeClubCardListByGeneralOrderIdNoOpR" +
            "esponse")]
        TestCinemaClubAPI.CinemaClubService.GetClubCardListResult GetLifeClubCardListByGeneralOrderIdNoOp(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaryCardSerivce/ActiveClubCard", ReplyAction="http://tempuri.org/ISecretaryCardSerivce/ActiveClubCardResponse")]
        TestCinemaClubAPI.CinemaClubService.ActiveCardResult ActiveClubCard(string CardCode, TestCinemaClubAPI.CinemaClubService.ClubSeriesInfo Info, System.Guid operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaryCardSerivce/ActiveClubCardNoOp", ReplyAction="http://tempuri.org/ISecretaryCardSerivce/ActiveClubCardNoOpResponse")]
        TestCinemaClubAPI.CinemaClubService.ActiveCardResult ActiveClubCardNoOp(string CardCode, TestCinemaClubAPI.CinemaClubService.ClubSeriesInfo Info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaryCardSerivce/GetCinemaClubCard", ReplyAction="http://tempuri.org/ISecretaryCardSerivce/GetCinemaClubCardResponse")]
        TestCinemaClubAPI.CinemaClubService.CinemaCardInfo GetCinemaClubCard(string CardCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaryCardSerivce/GetCinemaTicketList", ReplyAction="http://tempuri.org/ISecretaryCardSerivce/GetCinemaTicketListResponse")]
        TestCinemaClubAPI.CinemaClubService.CinemaTicketInfo[] GetCinemaTicketList(string mobile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecretaryCardSerivceChannel : TestCinemaClubAPI.CinemaClubService.ISecretaryCardSerivce, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecretaryCardSerivceClient : System.ServiceModel.ClientBase<TestCinemaClubAPI.CinemaClubService.ISecretaryCardSerivce>, TestCinemaClubAPI.CinemaClubService.ISecretaryCardSerivce {
        
        public SecretaryCardSerivceClient() {
        }
        
        public SecretaryCardSerivceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecretaryCardSerivceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretaryCardSerivceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretaryCardSerivceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestCinemaClubAPI.CinemaClubService.SecretaryCard[] GetSecretaryCardListByGeneralOrderId(out string errMsg, string orderId, System.Guid operatorId) {
            return base.Channel.GetSecretaryCardListByGeneralOrderId(out errMsg, orderId, operatorId);
        }
        
        public TestCinemaClubAPI.CinemaClubService.GetClubCardListResult GetLifeClubCardListByGeneralOrderId(string orderId, System.Guid operatorId) {
            return base.Channel.GetLifeClubCardListByGeneralOrderId(orderId, operatorId);
        }
        
        public TestCinemaClubAPI.CinemaClubService.GetClubCardListResult GetLifeClubCardListByGeneralOrderIdNoOp(string orderId) {
            return base.Channel.GetLifeClubCardListByGeneralOrderIdNoOp(orderId);
        }
        
        public TestCinemaClubAPI.CinemaClubService.ActiveCardResult ActiveClubCard(string CardCode, TestCinemaClubAPI.CinemaClubService.ClubSeriesInfo Info, System.Guid operatorId) {
            return base.Channel.ActiveClubCard(CardCode, Info, operatorId);
        }
        
        public TestCinemaClubAPI.CinemaClubService.ActiveCardResult ActiveClubCardNoOp(string CardCode, TestCinemaClubAPI.CinemaClubService.ClubSeriesInfo Info) {
            return base.Channel.ActiveClubCardNoOp(CardCode, Info);
        }
        
        public TestCinemaClubAPI.CinemaClubService.CinemaCardInfo GetCinemaClubCard(string CardCode, string Password) {
            return base.Channel.GetCinemaClubCard(CardCode, Password);
        }
        
        public TestCinemaClubAPI.CinemaClubService.CinemaTicketInfo[] GetCinemaTicketList(string mobile) {
            return base.Channel.GetCinemaTicketList(mobile);
        }
    }
}
